### ISSUE TITLE
How to install those files ?

### ISSUE THREAD

**Issue by hachbani2019** [ufz/vtkGUISupportQt#1]
Hi,

Trying to build rtab-map ( https://github.com/introlab/rtabmap_ros ), I get an error that vtkGUISupportQt is missing. SO I'm trying to build your files as it's what I guess to be the solution to my problem. 

THe link of my issue if you want to know more: https://github.com/introlab/rtabmap_ros/issues/312

Thanks,

**Comment by bilke** [comment]
This is not the official vtkGUISupportQt-library. See https://vtk.org
